[build]
  base = ""
  command = "bash build.sh"
  publish = "app/dist"

[functions]
  directory = "app/netlify/functions"

[functions."remove-bg"]
  runtime = "python3.11"

[[redirects]]
  from = "/wardrobe/*"
  to = "/wardrobe/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
